#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# audit-all.sh -- Cloud Cost Audit Orchestrator
#
# Detects which cloud provider CLIs are installed and authenticated, runs
# each available provider's audit, then produces a cross-cloud summary.
#
# Exit codes:
#   0  All available audits completed successfully.
#   1  One or more audits failed.
#   2  No provider CLIs are available -- nothing to audit.
# ---------------------------------------------------------------------------
set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve script directory and source shared libraries.
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${SCRIPT_DIR}/lib"
OUTPUT_DIR="${SCRIPT_DIR}/output"

# shellcheck source=lib/colors.sh
source "${LIB_DIR}/colors.sh"
# shellcheck source=lib/prereqs.sh
source "${LIB_DIR}/prereqs.sh"
# shellcheck source=lib/table.sh
source "${LIB_DIR}/table.sh"
# shellcheck source=lib/json.sh
source "${LIB_DIR}/json.sh"

# Ensure the output directory exists.
mkdir -p "${OUTPUT_DIR}"

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------
echo ""
echo "${BOLD}=======================================${RESET}"
echo "${BOLD}   Cloud Cost Audit -- Full Scan${RESET}"
echo "${BOLD}=======================================${RESET}"
echo ""
echo "  Date:   $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "  Host:   $(hostname 2>/dev/null || echo 'unknown')"
echo ""

# ---------------------------------------------------------------------------
# Detect available providers
# ---------------------------------------------------------------------------
declare -A PROVIDER_STATUS   # "available" | "no_cli" | "no_auth" | "ran" | "failed"
PROVIDERS=(aws gcp azure)

section "Checking prerequisites"

# jq is required for JSON processing across all audits.
if ! require_bin jq; then
    warn "jq is not installed. JSON output will still be generated by the"
    warn "built-in json.sh library, but some audit scripts may need jq for"
    warn "parsing provider CLI output. Proceeding anyway."
fi

# -- AWS --
info "Checking AWS..."
if require_auth_aws 2>/dev/null; then
    PROVIDER_STATUS[aws]="available"
    ok "AWS is available."
elif command -v aws &>/dev/null; then
    PROVIDER_STATUS[aws]="no_auth"
    warn "AWS CLI found but not authenticated. Skipping AWS audits."
else
    PROVIDER_STATUS[aws]="no_cli"
    warn "AWS CLI not installed. Skipping AWS audits."
fi

# -- GCP --
info "Checking GCP..."
if require_auth_gcp 2>/dev/null; then
    PROVIDER_STATUS[gcp]="available"
    ok "GCP is available."
elif command -v gcloud &>/dev/null; then
    PROVIDER_STATUS[gcp]="no_auth"
    warn "gcloud CLI found but not authenticated. Skipping GCP audits."
else
    PROVIDER_STATUS[gcp]="no_cli"
    warn "gcloud CLI not installed. Skipping GCP audits."
fi

# -- Azure --
info "Checking Azure..."
if require_auth_azure 2>/dev/null; then
    PROVIDER_STATUS[azure]="available"
    ok "Azure is available."
elif command -v az &>/dev/null; then
    PROVIDER_STATUS[azure]="no_auth"
    warn "Azure CLI found but not authenticated. Skipping Azure audits."
else
    PROVIDER_STATUS[azure]="no_cli"
    warn "Azure CLI not installed. Skipping Azure audits."
fi

# Count how many providers are available.
available_count=0
for p in "${PROVIDERS[@]}"; do
    [[ "${PROVIDER_STATUS[$p]}" == "available" ]] && (( available_count++ ))
done

if (( available_count == 0 )); then
    echo ""
    err "No cloud providers are available. Install and authenticate at least one"
    err "provider CLI to run an audit. See README.md for setup instructions."
    exit 2
fi

info "${available_count} provider(s) ready for audit."

# ---------------------------------------------------------------------------
# Run provider audits
# ---------------------------------------------------------------------------
audit_failures=0

run_provider_audit() {
    local provider="$1"
    local script_path="${SCRIPT_DIR}/${provider}/audit-${provider}.sh"

    section "Running ${provider^^} audit"

    if [[ ! -x "$script_path" ]]; then
        warn "Audit script not found or not executable: ${script_path}"
        warn "Skipping ${provider^^} audit (no audit script yet)."
        PROVIDER_STATUS[$provider]="skipped"
        return 0
    fi

    if "$script_path"; then
        PROVIDER_STATUS[$provider]="ran"
        ok "${provider^^} audit completed successfully."
    else
        PROVIDER_STATUS[$provider]="failed"
        err "${provider^^} audit exited with errors."
        (( audit_failures++ ))
    fi
}

for provider in "${PROVIDERS[@]}"; do
    if [[ "${PROVIDER_STATUS[$provider]}" == "available" ]]; then
        run_provider_audit "$provider"
    fi
done

# ---------------------------------------------------------------------------
# Cross-cloud summary
# ---------------------------------------------------------------------------
summary_script="${SCRIPT_DIR}/summary/summarize.sh"
if [[ -x "$summary_script" ]]; then
    section "Generating cross-cloud summary"
    if "$summary_script"; then
        ok "Summary generated."
    else
        warn "Summary script exited with errors."
    fi
fi

# ---------------------------------------------------------------------------
# Final status report
# ---------------------------------------------------------------------------
section "Audit Complete"

echo ""
table_print \
    "Provider|Status|Detail" \
    "AWS|$(
        case "${PROVIDER_STATUS[aws]}" in
            ran)      echo "${GREEN}OK${RESET}|Audit completed" ;;
            failed)   echo "${RED}FAIL${RESET}|Audit had errors" ;;
            skipped)  echo "${YELLOW}SKIP${RESET}|No audit script" ;;
            no_auth)  echo "${YELLOW}SKIP${RESET}|Not authenticated" ;;
            no_cli)   echo "${DIM}SKIP${RESET}|CLI not installed" ;;
            *)        echo "SKIP|${PROVIDER_STATUS[aws]}" ;;
        esac
    )" \
    "GCP|$(
        case "${PROVIDER_STATUS[gcp]}" in
            ran)      echo "${GREEN}OK${RESET}|Audit completed" ;;
            failed)   echo "${RED}FAIL${RESET}|Audit had errors" ;;
            skipped)  echo "${YELLOW}SKIP${RESET}|No audit script" ;;
            no_auth)  echo "${YELLOW}SKIP${RESET}|Not authenticated" ;;
            no_cli)   echo "${DIM}SKIP${RESET}|CLI not installed" ;;
            *)        echo "SKIP|${PROVIDER_STATUS[gcp]}" ;;
        esac
    )" \
    "Azure|$(
        case "${PROVIDER_STATUS[azure]}" in
            ran)      echo "${GREEN}OK${RESET}|Audit completed" ;;
            failed)   echo "${RED}FAIL${RESET}|Audit had errors" ;;
            skipped)  echo "${YELLOW}SKIP${RESET}|No audit script" ;;
            no_auth)  echo "${YELLOW}SKIP${RESET}|Not authenticated" ;;
            no_cli)   echo "${DIM}SKIP${RESET}|CLI not installed" ;;
            *)        echo "SKIP|${PROVIDER_STATUS[azure]}" ;;
        esac
    )"
echo ""

if (( audit_failures > 0 )); then
    err "${audit_failures} audit(s) had errors. Review output above."
    exit 1
fi

ok "All audits completed successfully."
exit 0
